/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.example.longshotscreen.utils;

import android.graphics.Bitmap;

public class ImageMap2d {
	private Bitmap mBitmap;
	public int mHeight;
	public int mWidth;

	public ImageMap2d(Bitmap bitmap, int width, int height) {
		mBitmap = bitmap;
		mWidth = width;
		mHeight = height;
	}

	public int GetPixel(int x, int y) {
		return mBitmap.getPixel(x, y);
	}

	public boolean IsBitmapRecycle() {
		return mBitmap.isRecycled();
	}

	public void SetPixel(int x, int y, int color) {
		mBitmap.setPixel(x, y, color);
	}
}
