/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.example.longshotscreen.manager;

import android.content.Intent;

public class NoticeParam {
	private String mClassName;
	private String mContent;
	private int mIcon;
	private int mId;
	private Intent mIntent;
	private String mParam;
	private String mPkgName;
	private String mTicker;
	private String mTitle;

	public NoticeParam(int id, String title, String content, Intent intent, int icon, String ticker) {
		mId = id;
		mTitle = title;
		mContent = content;
		mIntent = intent;
		mIcon = icon;
		mTicker = ticker;
	}

	public String getContent() {
		return mContent;
	}

	public int getIcon() {
		return mIcon;
	}

	public int getId() {
		return mId;
	}

	public Intent getIntent() {
		return mIntent;
	}

	public String getTicker() {
		return mTicker;
	}

	public String getTitle() {
		return mTitle;
	}

	public String toString() {
		return "NoticeParam [mId=" + mId + ", mTitle=" + mTitle + ", " + "mContent=" + mContent + ", mPkgName=" + mPkgName + ", mClassName=" + mClassName + ", mParam=" + mParam + ", mTicker=" + mTicker + ", mIntent=" + mIntent + ", mIcon=" + mIcon + "]";
	}
}
