package com.prize.app.beans;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

import org.xutils.db.annotation.Column;
import org.xutils.db.annotation.Table;

import java.io.Serializable;


/**
 * 已领取应用存入数据的对象
 */
@Table(name = "EarnPoints360Bean")
public class EarnPoints360Bean implements Serializable{
    @Column(name = "id",autoGen = true, isId = true)
    public int id;
    @Column(name = "packageName")
    public String packageName;
    @Column(name = "gson")
    public String gson;
    @Column(name = "timeStamp")
    public long timeStamp;


}
