/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_goodix_device_FpDevice */

#ifndef _Included_com_goodix_device_FpDevice
#define _Included_com_goodix_device_FpDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_goodix_device_FpDevice
 * Method:    native_setup
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_goodix_device_FpDevice_native_1setup
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_goodix_device_FpDevice
 * Method:    native_release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_goodix_device_FpDevice_native_1release
  (JNIEnv *, jobject);

/*
 * Class:     com_goodix_device_FpDevice
 * Method:    query
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_goodix_device_FpDevice_query
  (JNIEnv *, jobject);

/*
 * Class:     com_goodix_device_FpDevice
 * Method:    register
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_goodix_device_FpDevice_register
  (JNIEnv *, jobject);

/*
 * Class:     com_goodix_device_FpDevice
 * Method:    cancelRegister
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_goodix_device_FpDevice_cancelRegister
  (JNIEnv *, jobject);

/*
 * Class:     com_goodix_device_FpDevice
 * Method:    resetRegister
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_goodix_device_FpDevice_resetRegister
  (JNIEnv *, jobject);

/*
 * Class:     com_goodix_device_FpDevice
 * Method:    saveRegister
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_goodix_device_FpDevice_saveRegister
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_goodix_device_FpDevice
 * Method:    saveRegister
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_goodix_device_FpDevice_setMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_goodix_device_FpDevice
 * Method:    SendCmd
 * Signature: (I;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_goodix_device_FpDevice_SendCmdLegac
  (JNIEnv *, jobject , jint , jstring , jstring);


/*
 * Class:     com_goodix_device_FpDevice
 * Method:    SendCmd
 * Signature: (I;Ljava/lang/String;Ljava/lang/String;[I])I
 */
JNIEXPORT jint JNICALL Java_com_goodix_device_FpDevice_SendCmd
  (JNIEnv *, jobject , jint , jstring , jstring, jintArray);

/*
 * Class:     com_goodix_device_FpDevice
 * Method:    recognize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_goodix_device_FpDevice_recognize
  (JNIEnv *, jobject);

/*
 * Class:     com_goodix_device_FpDevice
 * Method:    delete
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_goodix_device_FpDevice_delete
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_goodix_device_FpDevice
 * Method:    getInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_goodix_device_FpDevice_getInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_goodix_device_FpDevice
 * Method:    checkPassword
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_goodix_device_FpDevice_checkPassword
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_goodix_device_FpDevice
 * Method:    getPermission
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_goodix_device_FpDevice_getPermission
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_goodix_device_FpDevice
 * Method:    changePassword
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_goodix_device_FpDevice_changePassword
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_goodix_device_FpDevice
 * Method:    cancelRecognize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_goodix_device_FpDevice_cancelRecognize
  (JNIEnv *, jobject);
//[zhaoyi add 20140731, get screen state for set chip work mode
JNIEXPORT jint JNICALL Java_com_goodix_device_FpDevice_sendScreenState
  (JNIEnv *, jobject, jint);
//]zhaoyi add 20140731, get screen state for set chip work mode
#ifdef __cplusplus
}
#endif
#endif
