/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.example.longshotscreen.services;

import android.app.Notification;
import android.app.PendingIntent;
import android.app.Service;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.IBinder;
import com.example.longshotscreen.utils.Log;

import com.example.longshotscreen.MainActivity;
import com.example.longshotscreen.R;
import com.example.longshotscreen.manager.SuperShotFloatViewManager;

public class FunnyShotService extends Service {
	private SuperShotFloatViewManager mFloatViewManager;
	private GlobalReceiver mGlobalReceiver;
	public IBinder onBind(Intent intent) {
		return null;
	}

	public void onCreate() {
		super.onCreate();
		mFloatViewManager = SuperShotFloatViewManager.getInstance(getApplicationContext());
		mFloatViewManager.startFunnyShot();
		
		mGlobalReceiver = new GlobalReceiver();
		mGlobalReceiver.register();
	}

	
	//public int onStartCommand(Intent intent, int flag, int startId) {
		/*
		Notification notification = new Notification(R.drawable.main_menu_funny_shot_normal,
				getString(R.string.app_name), System.currentTimeMillis());

		PendingIntent pendingintent = PendingIntent.getActivity(this, 0,
				new Intent(this, MainActivity.class), 0);
		notification.setLatestEventInfo(this, "supershot", "请保持程序在后台运行",
				pendingintent);
		startForeground(0x111, notification);
 */
	//	return 2;
	//}

	@Override
	public int onStartCommand(Intent intent, int flags, int startId) {
		//return super.onStartCommand(intent, flags, startId);
		return 2;
	}

	public void onDestroy() {
		mFloatViewManager.exitFunnyShot();
		//stopForeground(true);
		super.onDestroy();
		
		mGlobalReceiver.unregister();
		mGlobalReceiver = null;
	}
	
	public class GlobalReceiver extends BroadcastReceiver
	{
		private static final String ALARM_ALERT = "com.android.deskclock.ALARM_ALERT";

		public GlobalReceiver()
		{
		}

		public void onReceive(Context paramContext, Intent paramIntent)
		{
			FunnyShotService.this.stopSelf();
		}

		public void register()
		{
			IntentFilter localIntentFilter = new IntentFilter();
			//localIntentFilter.addAction("android.intent.action.FONT_CHANGED");
			//localIntentFilter.addAction("android.intent.action.SKIN_CHANGED");
			//localIntentFilter.addAction("com.android.deskclock.ALARM_ALERT");
			/*PRIZE-FrameRecorder-SCREEN-OFF-Stop-Recorder-shiyicheng-2015-12-15-start*/
			localIntentFilter.addAction(Intent.ACTION_SCREEN_OFF);
			/*PRIZE-FrameRecorder-SCREEN-OFF-Stop-Recorder-shiyicheng-2015-12-15-end*/
			FunnyShotService.this.registerReceiver(this, localIntentFilter);
		}

		public void unregister()
		{
			FunnyShotService.this.unregisterReceiver(this);
		}
	}
}
