/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.example.longshotscreen.services;

import android.app.Service;
import android.content.Intent;
import android.os.IBinder;
import com.example.longshotscreen.utils.Log;
/*PRIZE-OneHandMode-liyu-2016-01-04-start*/
import android.provider.Settings;
/*PRIZE-OneHandMode-liyu-2016-01-04-end*/

import com.example.longshotscreen.manager.SuperShotMenuManager;

public class MainFloatMenuService extends Service {
	private SuperShotMenuManager mSuperShotMenuManager;

	public IBinder onBind(Intent intent) {
		return null;
	}

	public void onCreate() {
		super.onCreate();
		Log.i("MainFloatMenuService", " onCreate ");
		/*PRIZE-OneHandMode-liyu-2016-01-04-start*/
		//Settings.Global.putString(getContentResolver(),
		//						Settings.Global.MIN_DISPLAY_DEVICES, "NULL");
		/*PRIZE-OneHandMode-liyu-2016-01-04-end*/
		mSuperShotMenuManager = SuperShotMenuManager.getInstance(getApplicationContext());
		mSuperShotMenuManager.addView();
	}

	public int onStartCommand(Intent intent, int flag, int startId) {
		Log.i("MainFloatMenuService", " onStartCommand " + intent);
		/*PRIZE-LongShotScreen-float-menu-not-dispaly-shiyicheng-2015-12-17-start*/
		if(mSuperShotMenuManager != null){
			mSuperShotMenuManager.removeView();
			Log.i("MainFloatMenuService", " onStartCommand removeView");
		}
		mSuperShotMenuManager = SuperShotMenuManager.getInstance(getApplicationContext());
		mSuperShotMenuManager.addView();
		/*PRIZE-LongShotScreen-float-menu-not-dispaly-shiyicheng-2015-12-17-end*/
		return super.onStartCommand(intent, flag, startId);
	}

	public void onDestroy() {
		Log.i("MainFloatMenuService", " onDestroy ");
		if(mSuperShotMenuManager != null){
			mSuperShotMenuManager.removeView();
			/*PRIZE-LongShotScreen-float-menu-not-dispaly-shiyicheng-2015-12-17-start*/
			mSuperShotMenuManager = null;
			/*PRIZE-LongShotScreen-float-menu-not-dispaly-shiyicheng-2015-12-17-end*/
		}
		super.onDestroy();
	}
}
