/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.example.longshotscreen.services;

import android.app.Service;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.IBinder;
import com.example.longshotscreen.utils.Log;

import com.example.longshotscreen.manager.SuperShotFloatViewManager;

public class ScrollShotService extends Service {
	private static final String TAG = "ScrollShotService";
	private SuperShotFloatViewManager mFloatViewManager;
	private ScrollGlobalReceiver mScrollGlobalReceiver;
	public IBinder onBind(Intent intent) {
		return null;
	}

	public void onCreate() {
		super.onCreate();
		Log.d(TAG, "[onCreate]");
		mFloatViewManager = SuperShotFloatViewManager.getInstance(getApplicationContext());
		mFloatViewManager.startScrollShot();
		
		mScrollGlobalReceiver = new ScrollGlobalReceiver();
		mScrollGlobalReceiver.register();
	}

	public int onStartCommand(Intent intent, int flag, int startId) {
		return super.onStartCommand(intent, flag, startId);
	}

	public void onDestroy() {
		mFloatViewManager.exitScrollShot();
		super.onDestroy();
		
		mScrollGlobalReceiver.unregister();
		mScrollGlobalReceiver = null;
	}
	
	public class ScrollGlobalReceiver extends BroadcastReceiver
	{
		private static final String ALARM_ALERT = "com.android.deskclock.ALARM_ALERT";

		public ScrollGlobalReceiver()
		{
		}

		public void onReceive(Context paramContext, Intent paramIntent)
		{
			ScrollShotService.this.stopSelf();
		}

		public void register()
		{
			IntentFilter localIntentFilter = new IntentFilter();
			//localIntentFilter.addAction("android.intent.action.FONT_CHANGED");
			//localIntentFilter.addAction("android.intent.action.SKIN_CHANGED");
			//localIntentFilter.addAction("com.android.deskclock.ALARM_ALERT");
			/*PRIZE-FrameRecorder-SCREEN-OFF-Stop-Recorder-shiyicheng-2015-12-15-start*/
			localIntentFilter.addAction(Intent.ACTION_SCREEN_OFF);
			/*PRIZE-FrameRecorder-SCREEN-OFF-Stop-Recorder-shiyicheng-2015-12-15-end*/
			ScrollShotService.this.registerReceiver(this, localIntentFilter);
		}

		public void unregister()
		{
			ScrollShotService.this.unregisterReceiver(this);
		}
	}
}
