/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.example.longshotscreen.ui;

import android.widget.RelativeLayout;
import android.os.Handler;
import android.content.Context;
import android.util.AttributeSet;
import android.content.res.Configuration;

public class FunnyShotMainLayout extends RelativeLayout {
	private Handler mHandler;

	public FunnyShotMainLayout(Context context, AttributeSet attributeSet) {
		super(context, attributeSet);
	}

	private void sendExitMessage() {
		mHandler.sendEmptyMessage(0x458);
	}

	protected void onConfigurationChanged(Configuration configuration) {
		sendExitMessage();
	}

	public void setHandler(Handler handler) {
		mHandler = handler;
	}
}
